Repository googleapis/nodejs-datastore-kvstore, pull requests merged in 2022-05, with the labels that each got.

#307 chore: Change the Codeowner to cloud-native-db-dpes
  .github/CODEOWNERS
  .repo-metadata.json
Labels: api: datastore, size: xs

#317 build!: update library to use Node 12
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  package.json
  samples/package.json
Labels: api: datastore, size: m

#319 build: update repo-metadata
  .repo-metadata.json
  README.md
Labels: api: datastore, size: s
